### ISSUE TITLE
how to draw circles

### ISSUE THREAD

**Issue by tissatussa** [can-lehmann/owlkettle#104]
I see many widgets but it's unclear to me how to draw circels .. is it even possible ?

I discovered the **Cairo Path** widget in /examples/misc and i'm able to compile it. It's a nice example how to draw lines and change parameters with several options - the source code is good for learning !

I guess drawing circles can also be done with **Cairo**, but i have no clue .. maybe some `GTK` examples exist which can be ported to `Nim` / `Owlkettle` ?

**Comment by can-lehmann** [comment]
I reccomend looking at the `cairo.nim` file for a list of all supported cairo procs. For your case: https://github.com/can-lehmann/owlkettle/blob/main/owlkettle/cairo.nim#L168

**Comment by tissatussa** [comment]
@can-lehmann thanks, for me this .nim file is an abstract but i'll study it : indeed i see `proc circle*(ctx: CairoContext, x, y, r: float)`.

I just found https://github.com/Elteoremadebeethoven/pycairo-tutorial and thus also https://zetcode.com/gfx/pycairo/ : i guess i'll start with `Cairo` in `Python` and learn how to work with the functions and their arguments .. then i'll switch to Owlkettle circle, assuming it's about the same GTK properties etc.
