### ISSUE TITLE
Can't send notifications while using adwaita

### ISSUE THREAD

**Issue by jaredmontoya** [can-lehmann/owlkettle#139]
This is the error message you get when trying to send a notification while using brew or adw.brew to initialize an application.
```
Error: unhandled exception: Unable to send notification: The Application does not have 
an application id. Please pass the application id as the first parameter of the brew pr
ocedure. Example: brew("com.example.MyApplication", gui(App())) [IOError]
```
if you are using brew you can follow the instructions in the error message to resolve this error, but if you try to do the same for adw.brew it will throw ```Error: type mismatch```.

**Comment by can-lehmann** [comment]
The required overload has been added in https://github.com/can-lehmann/owlkettle/commit/7648493350742f00c6bc2b5d622418f623ee51bf. You should be able to just replace brew with adw.brew.
