### ISSUE TITLE
text_view widget : display multiple lines ?

### ISSUE THREAD

**Issue by tissatussa** [can-lehmann/owlkettle#142]
i'm trying to create some script based on the `text_view.nim` code : i stripped your example code (which works) by removing all buttons but one : my "GO" button just adds the text "HELLO WORLD" (on 2 lines) to the `app.buffer`, but it seems the text area is only updated after the last line of the `proc clicked()` is processed .. for test i put a 1 second delay by `sleep()` : but BOTH words "HELLO" and "WORLD" are displayed AFTER the delay - i expected "HELLO" to be displayed immediately, then after 1 second "WORLD" should be displayed ? Maybe i should use some `flush()` method here ?

finally i want to use such code to display output of a running process - my code to do that already works. But i have no clue how to integrate it into Owlkettle, using a text area .. it seems simple, i'm probably missing something - i'm using the newest Owlkettle version.

```nim
import std/os
import owlkettle
import owlkettle/adw

viewable App:
  buffer: TextBuffer
  monospace: bool = false
  cursorVisible: bool = true
  editable: bool = false
  acceptsTab: bool = true
  indent: int = 0
  sensitive: bool = true
  sizeRequest: tuple[x, y: int] = (-1, -1) 
  tooltip: string = "" 

method view(app: AppState): Widget =
  result = gui:
    Window:
      title = "*** TEST ***"
      defaultSize = (1100, 600)
      HeaderBar {.addTitlebar.}:
        Button {.addLeft.}:
          style = [ButtonFlat]
          text = "GO"
          proc clicked() =
            app.buffer.text = app.buffer.text & "HELLO" & "\n"
            sleep(1000)
            app.buffer.text = app.buffer.text & "WORLD" & "\n"

      ScrolledWindow:
        TextView:
          margin = 12
          buffer = app.buffer
          monospace = app.monospace
          cursorVisible = app.cursorVisible
          editable = app.editable
          acceptsTab = app.acceptsTab
          indent = app.indent
          sensitive = app.sensitive
          tooltip = app.tooltip
          sizeRequest = app.sizeRequest
          proc changed() = discard
        

let buffer = newTextBuffer()

buffer.text = "first text line\n"

adw.brew(gui(App(buffer = buffer)))
```

[ i'm on Xubuntu 22.04 ]

**Comment by can-lehmann** [comment]
Yes, you are right that you need some kind of `flush` method: Event handlers only redraw the gui once they are completed. You can use `app.redraw()` to manually trigger a redraw (in your case before the call to `sleep`).

Note though, that if you block inside event handlers the gui will become unresponsive.

**Comment by tissatussa** [comment]
> You can use app.redraw() to manually trigger a redraw (in your case before the call to sleep)

that does NOT work .. did you try it ? I just put `discard app.redraw()` before my `sleep()`

**Comment by can-lehmann** [comment]
Apparently GTK does not redraw immediately after widgets are updated. So you need to give it some time to redraw. If you insist on having blocking callbacks, one way to do this is calling `g_main_context_iteration` a few times and hoping for the best.

This code works for me on Nim 1.6.8 when importing `owlkettle/bindings/gtk`.

```nim
discard app.redraw()
for it in 0..<10:
  discard g_main_context_iteration(GMainContext(nil), cbool(ord(true)))
sleep(1000)
```

Please **DO NOT** use it for anything serious. Event handler should never block. This is just a workaround you could use while prototyping. The proper way to do this would be to either use asynchronous (for sleep e.g. `addGlobalTimeout`) execution or threading.

**Comment by can-lehmann** [comment]
There is a really simple example of how to use threading here: https://github.com/can-lehmann/owlkettle/blob/main/examples/misc/threading.nim

**Comment by tissatussa** [comment]
thanks !
your threading example works, i shall study it.
btw. that example Nim code only works with Nim v2 .. until now i had v1.6.12 and it gives an error :

`owlkettle.nim(118, 5) Error: undeclared identifier: '=wasMoved'`

**Comment by tissatussa** [comment]
i combined the thread script with my code and compiled with..

`nim c --threads:on --gc:orc --path:. ./myscript.nim`

(adding the options `--threads:on` and `--gc:orc`) ..but the result does NOT work : in `threadProc()` i just change the buffer text but it gives a severe error after clicking my GO button :

```
Traceback (most recent call last)
/home/roelof/Compiled/owlkettle-main-v2.2.0/examples/widgets/uci.nim(20) threadProc
/home/roelof/Compiled/owlkettle-main-v2.2.0/owlkettle/widgets.nim(2335) text=
/home/roelof/Compiled/owlkettle-main-v2.2.0/owlkettle/widgetutils.nim(54) eventCallback
/home/roelof/Compiled/owlkettle-main-v2.2.0/owlkettle/widgetutils.nim(39) redraw
/home/roelof/Compiled/owlkettle-main-v2.2.0/owlkettle/widgetdef.nim(78) redraw
/home/roelof/.choosenim/toolchains/nim-2.0.0/lib/system/arc.nim(179) nimDestroyAndDispose
/home/roelof/.choosenim/toolchains/nim-2.0.0/lib/system/arc.nim(179) nimDestroyAndDispose
/home/roelof/.choosenim/toolchains/nim-2.0.0/lib/system/orc.nim(486) nimDecRefIsLastCyclicDyn
/home/roelof/.choosenim/toolchains/nim-2.0.0/lib/system/orc.nim(469) rememberCycle
/home/roelof/.choosenim/toolchains/nim-2.0.0/lib/system/orc.nim(148) unregisterCycle
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault (core dumped)
```

i tried to catch this error by a `try-except` clause but no error message is displayed !?
it seems in `threadProc()` the `app.buffer.text` can be read (i echoed its value) but it can not be changed : the `SIGSEGV` error comes..

here's the script:

```nim
import std/os
import owlkettle

viewable App:
  buffer: TextBuffer
  monospace: bool = false
  cursorVisible: bool = true
  editable: bool = true
  acceptsTab: bool = true
  indent: int = 0
  sensitive: bool = true
  sizeRequest: tuple[x, y: int] = (-1, -1) 
  tooltip: string = "" 

when compileOption("threads"):
  var thread: Thread[AppState]

proc threadProc(app: AppState) {.thread.} =
  while true:
    app.buffer.text = app.buffer.text & "HELLO" & "\n"  # gives error, but try-except does NOT catch it
    app.redrawFromThread()
    sleep(1000)

method view(app: AppState): Widget =
  result = gui:
    Window:
      title = "*** TEST ***"
      defaultSize = (1100, 600)

      HeaderBar {.addTitlebar.}:
        Button {.addLeft.}:
          style = [ButtonFlat]
          text = "GO"

          proc clicked() =
            when compileOption("threads"):
              createThread(thread, threadProc, app)

      ScrolledWindow:
        TextView:
          margin = 12
          buffer = app.buffer
          monospace = app.monospace
          cursorVisible = app.cursorVisible
          editable = app.editable
          acceptsTab = app.acceptsTab
          indent = app.indent
          sensitive = app.sensitive
          tooltip = app.tooltip
          sizeRequest = app.sizeRequest
          proc changed() = discard
        

when compileOption("threads") and (defined(gcOrc) or defined(gcArc)):
  let buffer = newTextBuffer()
  buffer.text = "first text line\n"
  brew(gui(App(buffer = buffer)))
else:
  quit "Compile with --threads:on and --gc:orc to enable threads"
```
