### ISSUE TITLE
Fix some examples

### ISSUE THREAD

**Issue by wada3n** [can-lehmann/owlkettle#152]
H,
I'm new to Nim and GTK, I'm also a big fan of working through examples to learn new programming languages. I think it's a great way to get a feel for the syntax and semantics of a language.
I'm writing to request a fix for some examples . BTW I'm a big fan of your work on this library, and I think it's a great resource for Nim gui developers.

I've noticed a few errors in the examples :
**1-** [examples/widgets/adw/entry_row.nim](https://github.com/can-lehmann/owlkettle/blob/main/examples/widgets/adw/entry_row.nim), 

> Error: undeclared identifier: 'EntryRow'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 9): 'Entry'
 (3, 9): 'EntryError'

**2-** [examples/widgets/adw/switch_row.nim](https://github.com/can-lehmann/owlkettle/blob/main/examples/widgets/adw/switch_row.nim)

> Error: undeclared identifier: 'SwitchRow'
candidates (edit distance, scope distance); see '--spellSuggest': 
 (3, 9): 'Switch'

Thank you for your time and consideration.

**Comment by can-lehmann** [comment]
Did you compile with `-d:adwminor:2`/`-d:adwminor:4` respectively?

**Comment by wada3n** [comment]
Yep,it worked 😄
As I said I am a beginner, so excuse my ignorance.
I have now looked at the code and found its related to Adwaita 1.x version. 
Thank you very much again.
