### ISSUE TITLE
won't compile unless using arc/orc

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#176]
if i use any memory management besides `--mm:arc` or `--mm:orc` i get:

```
/home/itwrx/.nimble/pkgs2/owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38/owlkettle/bindings/gtk.nim(419, 23) template/generic instantiation of `crossVersionDestructor` from here
/home/itwrx/.nimble/pkgs2/owlkettle-3.0.0-2319432a190a50ade29f85b1451099b08e71ab38/owlkettle/common.nim(120, 5) Error: signature for '=destroy' must be proc[T: object](x: var T)
```

this even happens with the owlkettle readme example.

I used: `nim c --mm:refc owlkettle_readme_example.nim`

Nim Compiler Version 2.2.0 [Linux: amd64]

thanks

**Comment by can-lehmann** [comment]
It seems like it should be pretty straight forward to fix. Add a check for arc/orc here: https://github.com/can-lehmann/owlkettle/blob/main/owlkettle/common.nim#L121. PR welcome, please check that it actually works though; I might be mistaken.
