### ISSUE TITLE
How to set up shortcuts for buttons?

### ISSUE THREAD

**Issue by kulkesk** [can-lehmann/owlkettle#20]
I looked everywhere in the examples and still i can't find how to set up shortcuts for buttons

**Comment by can-lehmann** [comment]
The development version of owlkettle has a `shortcut` field for buttons. You can use it to set a keyboard shortcut for buttons. The format is the same one that GTK uses https://docs.gtk.org/gtk4/func.accelerator_parse.html

**Comment by can-lehmann** [comment]
I just added a short example for how to use the `shortcut` field to the widget documentation for the `Button` widget.

**Comment by kulkesk** [comment]
Thank you very much! Can't wait to see how this lovely library will evolve over time
