### ISSUE TITLE
How to work with key press events

### ISSUE THREAD

**Issue by ghostcrafter551** [can-lehmann/owlkettle#23]
Hi,
I followed the tutorial to get started with Owlkettle and created the ToDo application. Now I wonder if I could bind the 'Enter' key of my keyboard to have the same effect as clicking the '+' button. Is this possible in the current version or is this planned for the future? Maybe I overlooked something in the docs / tutorial.
Thanks you in advance.

**Comment by can-lehmann** [comment]
Thanks for trying out owlkettle! This is actually already possible (although a bit hidden). The `Entry` widget has an `activate` event which is triggered when the user presses the enter key. See https://github.com/can-lehmann/owlkettle/blob/main/docs/widgets.md#events-2

**Comment by ghostcrafter551** [comment]
This works perfectly and is exactly what I needed. Thank you for the quick response and this awesome library!
