### ISSUE TITLE
App doesn't quit when closing window

### ISSUE THREAD

**Issue by ire4ever1190** [can-lehmann/owlkettle#3]
When I close the window the app still stays running in the background, is there a way to run a callback when the window is closed so the app quits?

**Comment by can-lehmann** [comment]
I added a close event to the `Window` widget. See https://github.com/can-lehmann/owlkettle/blob/main/docs/widgets.md#example for an example of how to use it to quit the app when the window is closed.

**Comment by ire4ever1190** [comment]
Thanks, worked perfectly :+1:
