### ISSUE TITLE
Image widget missing?

### ISSUE THREAD

**Issue by zedeus** [can-lehmann/owlkettle#33]
There doesn't seem to be a widget for displaying images. Useful if not necessary for things like image viewers and music players that show covers. GTK has a few different ways of doing it, it would probably be a good idea to support a couple of variants with different tradeoffs. A way to support async image loading would be very nice as well, maybe using GdkPixbuf: https://docs.gtk.org/gdk-pixbuf/type_func.Pixbuf.new_from_stream_async.html

**Comment by can-lehmann** [comment]
You are correct. There is currently no widget for displaying images that are not icons. I will look into wrapping GdkPixbuf and creating a GtkImage based `Image` widget. In the meantime, you should be able to display images inside a `DrawingArea` using cairo.

**Comment by can-lehmann** [comment]
I added a `Picture` widget based on `GtkPicture` in https://github.com/can-lehmann/owlkettle/commit/a60893d267e5ac7923eee1a6a15a2f2f4a24ad83 (`GtkImage` seems to be only for use with icons).
Here is an example of a simple image viewer for how to use it: https://github.com/can-lehmann/owlkettle/blob/main/examples/widgets/picture.nim You can use [this overload of the loadPixbuf proc](https://github.com/can-lehmann/owlkettle/blob/main/owlkettle/widgets.nim#L468) to load a scaled image.

**Comment by zedeus** [comment]
Sweet, that was fast. How about loading several images at once asynchronously? Many image viewers support a gallery view where you can see many at once. This would require dynamically loading and unloading a lot of images on the fly, to avoid slowing down everything to a crawl and using gigabytes of memory to keep e.g. 10k pixbufs in memory.

**Comment by can-lehmann** [comment]
I added `loadPixbufAsync` in https://github.com/can-lehmann/owlkettle/commit/86bd2f813e5875c0686417730acbdd79f69eaebf. Note that even though it might look like it integrates with Nim's asyncdispatch module, I would not expect it to work well. Proper async support is a goal for owlkettle 3.0. For the time being, you can use `addCallback` like this: .https://github.com/can-lehmann/owlkettle/blob/main/examples/widgets/picture.nim#L74
