### ISSUE TITLE
Add support for setting custom css classes

### ISSUE THREAD

**Issue by PhilippMDoerner** [can-lehmann/owlkettle#36]
Wanted to add this issue mostly so we don't forget about it and because it's personally important to me.

Currently, there is no official way to set a custom CSS class to a widget, which you could style as you'd want.

There is an unofficial hacky way that we talked about (documented here for any future reader) - Use the `afterBuild` hook :

```nim
import owlkettle, owlkettle/gtk

viewable RedCounterButton:
  count: int = 0
  
  hooks:
    afterBuild:
      let
        internalWidget = state.unwrapInternalWidget()
        styleContext = gtk_widget_get_style_context(internalWidget)
      gtk_style_context_add_class(styleContext, "red-background")

method view(state: RedCounterButtonState): Widget =
  result = gui:
    Button:
      text = $state.count
      proc clicked() =
        state.count += 1

viewable App:
  discard

method view(app: AppState): Widget =
  result = gui:
    Window:
      RedCounterButton()

brew(gui(App()), stylesheets=["stylesheet.css"])
```
And in `stylesheet.css`:
```css
.red-background {
  background: #ff0000;
}
```

(This only works with the current head commit, current being 25.02.2023, for anyone trying to do this).

I'm honestly not sure how a "proper" solution would be implemented. Should we have some kind of static "cssClass" field on `WidgetState` that is assumed to be there and whose value gets transferred to the internal-widget during the `build` and `update` phases after the hooks have run?

**Comment by can-lehmann** [comment]
We already have the `style` field defined for some widgets. Adding support for custom css classes would basically involve

1. Removing all existing `style` fields
2. Add a new `BaseWidget.style: HashSet[StyleClass]` field (where `StyleClass` is `distinct string`)
3. Adding hooks to update the styles in `BaseWidget` as required
4. Updating the existing style enums to be just Constants of type `StyleClass`

Ideally though you would not have to write e.g. `style = toHashTable([ButtonSuggested])` every time you set a style, so adding a setter for `openArray[StyleClass]` might be nice.

**Comment by PhilippMDoerner** [comment]
For point 3 you mean property hooks on the style field, similar to the ones in sizeRequest?

**Comment by PhilippMDoerner** [comment]
Also, anything speaking against the usage of `converter`'s ?

**Comment by PhilippMDoerner** [comment]
Which hooks are all required for this?
The reason why I'm asking is because my current approach appears to have broken *all* propagation of CSS-classes to GTK widgets in my feature-branch.

I've set up the property hook for `style` on `BaseWidget`:
```nim
....
  hooks style:
    property:
      updateStyle(state, widget)
...
```
I also modified the updateStyle proc for debugging purposes:
```nim
....
proc updateStyle*[State, Widget](state: State, widget: Widget) =
  mixin classes
  echo "Update Style running"
  echo "Widget styles: ", widget.valStyle
  echo "State styles: ", state.style
  
  if widget.hasStyle:
    let ctx = gtk_widget_get_style_context(state.internalWidget)
    for styleClass in state.style - widget.valStyle:
      echo "Remove class ", styleClass
      gtk_style_context_remove_class(ctx, cstring($styleClass))
    for styleClass in widget.valStyle - state.style:
      echo "Add class ", styleClass
      gtk_style_context_add_class(ctx, cstring($styleClass))
    state.style = widget.valStyle
....
```
I then compiled the "counter"-example with it, and it does compile, but the "+" button is not colored correctly as if there were no css class on it.

When you inspect the styles you can see that there strangely are none:
![image](https://user-images.githubusercontent.com/65814317/223786814-a50d0b12-ccf7-4cd0-8797-1123ba7f9b2a.png)

Looking at the console-output I get from the echos, it prints out:
```txt
Update Style running
Widget styles: {}
State styles: {}
Update Style running
Widget styles: {}
State styles: {}
Update Style running
Widget styles: {}
State styles: {}
Update Style running
Widget styles: {}
State styles: {}
Update Style running
Widget styles: {}
State styles: {}
Update Style running
Widget styles: {suggested-action}
State styles: {suggested-action}
Update Style running
Widget styles: {}
State styles: {}
```
So it appears the class shows up briefly, and then immediately gets overridden by something?

**Comment by PhilippMDoerner** [comment]
Turns out that was one of those cases where you don't want to use a property field-hook you want to use (build,update)-field hooks

**Comment by can-lehmann** [comment]
> Also, anything speaking against the usage of `converter`'s ?

When using converters you loose the type safety gained by using a `distinct string` for the `StyleClass` type.

**Comment by PhilippMDoerner** [comment]
Only partially, as you'd want to make sure you're not mixing strings and StyleClass. but if that's too much already I can look into setters for this

**Comment by can-lehmann** [comment]
> Only partially, as you'd want to make sure you're not mixing strings and StyleClass. but if that's too much already I can look into setters for this

True. I think setters might be the better option here though. Requiring the user to write `StyleClass("my-class")` encourages them to declare the classes as global constants, which should generally lead to better code quality. I would also assume that the `toStyleClassSet*[T](strSet: T): HashSet[StyleClass]` converter could lead to some difficult to debug errors. Maybe just have a setter for `openArray[StyleClass]` and one for `HashSet[StyleClass]`.

**Comment by PhilippMDoerner** [comment]
Aye, currently implementing the setters.

As for whether the user should deal with StyleClass or not: I'm honestly not sure.
I can see the benefit of doing as you propose, that being having all css-classes as global consts. It gives *really* nice guarantees that class-names will always be correct and eliminates typo-bugs. But it also comes at the cost of flexibility.

I already have using SCSS written according to BEM rules in my head for the future of my application. 
I'd want to write css trees like:
```scss
.container{
  ... css rules for a container ...
  &__entry{
    ...css rules for a container entry...
    &--active{
      ... css rules for an active container entry...
    }
  }
}
```
And do so en-mass. 
In fact, chances are I'd want to generate css classes via scss-mixins quite liberally.

Having to enshrine all of that flexibility and generated css *also* in a type-system on top of that was something I instinctively tried to avoid in my first approach. I'm failing to properly articulate why I'm struggling with this...

I'll implement it with setters for now that demand the user convert from string to StyleClass as you suggested, maybe a proper reason will occur to me at a later date.

**Comment by PhilippMDoerner** [comment]
> > Turns out that was one of those cases where you don't want to use a property field-hook you want to use (build,update)-field hooks

I'd inline the proc using the inline pragma. The reason why I wouldn't want to copy-paste the proc- body into the place of the update-hook is because I kind of like this split.
The update-hook is there to define what operations need to be done on an update, not necessarily *how* they need to be done.
So currently it just defines that the styles must be updated via `updateStyles`.
How that update occurs, that's for `updateStyles` to define. 

Those are 2 separate responsibilities and I kind of like that they're split into separate procs.

**Comment by can-lehmann** [comment]
Implemented in https://github.com/can-lehmann/owlkettle/pull/40
