### ISSUE TITLE
[FR] Add Gtk.ColumnView to owlkettle widgets

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#43]
It seems that [Gtk.ColumnView](https://docs.gtk.org/gtk4/class.ColumnView.html) is the widget i need for the application i'm currently building, and future similar applications. 

I need to list a seq of objects in horizontal rows with each object field's data in a column with a header, and i need sorting and eventually filtering. It sounds like this is what ColumnView was made for. 

thanks

**Comment by ITwrx** [comment]
Hmmm, I may have "jumped the gun" on this issue... now i'm not so sure [Gtk.ListBox](https://docs.gtk.org/gtk4/class.ListBox.html) can't do everything i need. I wonder what the key differences are...

**Comment by can-lehmann** [comment]
I had a brief look at `Gtk.ColumnView`. From a UI perspective the major (and obvious) difference is that it presents the data in a table like format. This is not easily possible with a `ListBox`, especially when you want to allow the user to resize the columns. It might be possible to emulate something like this with the `Grid` widget (requires owlkettle devel) for now.

There is however also an important performance difference. `ColumnView` uses a `ListItemFactory` to [lazily only generate the widgets shown on screen](https://blog.gtk.org/2020/09/21/gtkcolumnview/). This should greatly improve performance for large datasets.

I agree that owlkettle should support `Gtk.ColumnView`. I already planned to support `Gtk.ListView` for owlkettle 3.0.0, so also supporting `Gtk.ColumnView` would be a natural extension of this plan. Especially for owlkettle, reducing the number of widgets that need to be updated on each redraw, could greatly improve performance.

The lazy rendering used by `Gtk.ColumnView` and `Gtk.ListView` will however also pose a challenge for supporting them, as they would be the first widgets in owlkettle that lazily render their items. There are both new API design questions and implementation issues that need to be explored here.

**Comment by ITwrx** [comment]
yeah, the lazy loading would be nice to use with pagination of the overall dataset in the gui. I went ahead and tried using Listbox for now, but it's not clear to me how to make the separate headers i created match up width-wise with ListBoxRow children, nor how to use the built-in header capability(?) mentioned in the docs.  Maybe i can abuse a grid. :)

Great to hear you're in favor of adding it. I'll look forward to any activity on this issue. I'm just coming back to nim after a long hiatus, so idk how much help i'll be on code, but let me know if there's anything else i can do to support this work.

thanks

**Comment by can-lehmann** [comment]
An initial implementation is finally available here: https://github.com/can-lehmann/owlkettle/commit/b2da2f4a656faae0ccd4ace3696caa0b5fb3e755
