### ISSUE TITLE
Macros `echo result.repr`

### ISSUE THREAD

**Issue by beef331** [can-lehmann/owlkettle#5]
I was going to make a PR to fix this but given that you have it in multiple positions I feel like you desire this behaviour. If so can it be moved behind a  `owlkettleDebug` flag to not pollute the terminal on project build?

**Comment by can-lehmann** [comment]
Moving the debugging statements behind an `owlkettle_debug`/`owlkettleDebug` flag is probably a good idea. I guess I did not expect people to start using this project for a while, so I did not bother doing something about them for the initial release ;)
