### ISSUE TITLE
[FR] enable hasStyle= for MessageDialog/BuiltInDialog

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#63]
I'm using MessageDialog as error message dialog for FileChooserDialog error. Would like to be able to style the text. It's currently pretty hard to even see the MessageDialog over the normal app window, at least with dark DE theme. Not super readable either.

thanks

**Comment by can-lehmann** [comment]
Should be fixed here: https://github.com/can-lehmann/owlkettle/commit/bec3124214faccd223defeb44515893d7c72c4e9

**Comment by ITwrx** [comment]
yes, it works now! thanks
