### ISSUE TITLE
Gtk.Switch buggy in f38

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#69]
hi,
An application i built [1] uses a Gtk.Switch and it's very buggy[2] in fedora 38, but works perfectly fine in f37 and ubuntu 22.04.1. I even built the binary in each OS for max compat. Do you think this might be an owlkettle issue, or i should report upstream?

thanks

f37 gtk: 4.8.3-1
ubuntu 22.04.1 gtk: 4.6.9
f38 gtk: 4.10.4-1 

1. My app's repo is not public yet, but i can provide src code or access to the private repo for you. Will be public and gpl3 when it's little website is done, and preferably f38 (newer gtk) supported.
2. doesn't always change when clicked, or changes the switch background color and position of slider, but other parts of my gui that depend on the state change don't update, or changes background color, but doesn't move slider, and variations of these.

**Comment by can-lehmann** [comment]
Might be related to https://github.com/can-lehmann/Graphing/issues/6, will have to investigate further though.

**Comment by ITwrx** [comment]
works great! thanks for the quick fix!
