### ISSUE TITLE
ListBoxRow cannot easily be interacted with keyboard.

### ISSUE THREAD

**Issue by beef331** [can-lehmann/owlkettle#7]
Using the arrow keys to navigate the following program the selection moves to the box, but it requires tab to move to the button then enter to interact with it.

```nim
import owlkettle

viewable App: discard

method view(app: AppState): Widget =
  result = gui:
    Window:
      default_size = (600, 400)
      proc close() = quit(1)
      ScrolledWindow:
        ListBox:
          for i in 0..10:
            ListBoxRow:
              Button:
                text = $i
                proc clicked() = echo i


brew(gui(App()))
```

**Comment by can-lehmann** [comment]
I added support for the activate event, which should fix this issue. You will have to provide callbacks for both the `Button.clicked` and `ListBoxRow.activate` events however (if you still want to react to mouse input). https://github.com/can-lehmann/owlkettle/blob/main/docs/widgets.md#example-7

**Comment by beef331** [comment]
Damn you work fast, thanks yet again.
