### ISSUE TITLE
MenuButton causes gtk error only in f38

### ISSUE THREAD

**Issue by ITwrx** [can-lehmann/owlkettle#70]
i have a `HeaderBar` with a viewable in it that contains a `MenuButton`. It works fine in fedora 37 and ubuntu 22.04.1, but causes the below gtk error when clicking on it in fedora 38. 

`Gtk-CRITICAL **: 06:39:43.725: _gtk_css_corner_value_get_x: assertion 'corner->class == &GTK_CSS_VALUE_CORNER' failed`

thanks

**Comment by can-lehmann** [comment]
It seems like this was a bug in GTK that should be fixed in the n

**Comment by ITwrx** [comment]
hmm, i think i forgot to check upstream for that... thanks
