### ISSUE TITLE
Missing destructors and memory deallocations

### ISSUE THREAD

**Issue by can-lehmann** [can-lehmann/owlkettle#76]
Review code for missing destructors and potential memory leaks. Known cases so far are

- GTK functions that return `cstring` (?)

**Comment by PhilippMDoerner** [comment]
Regarding the brew procedure with id.
It has a `  defer: g_object_unref(app.pointer)` line which unrefs the pointer of the application, no (owlkettle.nim line 214)?
So doesn't that mean that the brew procedure does unref things?

**Comment by PhilippMDoerner** [comment]
As for destructors for cstring returning procs... how would that one work in particular?
Create a type `Type ManagedCstring = distinct cstring` and define destructors for that and see about that being used everywhere instead of cstring?

**Comment by can-lehmann** [comment]
> Regarding the brew procedure with id. It has a ` defer: g_object_unref(app.pointer)` line which unrefs the pointer of the application, no (owlkettle.nim line 214)? So doesn't that mean that the brew procedure does unref things?

Oh you are right, I did not see that.

**Comment by can-lehmann** [comment]
> As for destructors for cstring returning procs... how would that one work in particular? Create a type `Type ManagedCstring = distinct cstring` and define destructors for that and see about that being used everywhere instead of cstring?

Well if value semantics worked, that would be the way to go. There are two options:

1. Hope that `=destroy` gets called correctly and use `distinct cstring`.
2. Manually deallocate.

You also **have** to check for each function's docs for whether the ownership of data returned by it is actually transferred to the caller. E.g. [here](https://docs.gtk.org/gtk4/method.Editable.get_text.html) this is not the case and you **must not** call free.

**Comment by PhilippMDoerner** [comment]
In that case that seems like a larger task and I'd like to split out dealing with cstring destructors in a separate PR

**Comment by PhilippMDoerner** [comment]
Okay, I've identified the cstring procs:
```txt
  gtk.nim 350: proc g_value_get_string*(value: ptr GValue): cstring
  gtk.nim 400: proc g_file_get_path*(file: GFile): cstring
  gtk.nim 401: proc g_file_get_uri*(file: GFile): cstring
  gtk.nim 536: proc gtk_widget_get_name*(widget: GtkWidget): cstring
  gtk.nim 598: proc gtk_editable_get_text*(entry: GtkWidget): cstring
    Do not manage memory, you do not own it (See: https://docs.gtk.org/gtk4/method.Editable.get_text.html)
  gtk.nim 605: proc gtk_entry_get_placeholder_text*(entry: GtkWidget): cstring
  gtk.nim 777: proc gtk_text_buffer_get_text*(buffer: GtkTextBuffer,
                               a, b: ptr GtkTextIter,
                               includeHiddenChars: cbool): cstring
  gtk.nim 927: proc gtk_string_object_get_string*(stringObject: GtkStringObject): cstring
  cairo.nim 146: proc cairo_status_to_string(status: CairoStatus): cstring
```
I'll edit this list with docs as I find them to figure out who all needs their memory managed.

**Comment by PhilippMDoerner** [comment]
I have a section of code, I just don't know how to place it in a manner that works.

```nim
import ./common
type OwnedGtkString* = distinct cstring

proc `=destroy`(cStr: OwnedGtkString) =
  if cStr.cstring.isNil():
    return
  
  g_free(pointer(cStr))

proc `=copy`*(dest: var OwnedGtkString, source: OwnedGtkString) =
  let areSameObject = pointer(source) == pointer(dest)
  if areSameObject:
    return
  
  `=destroy`(dest)
  wasMoved(dest)
  
  dest = source

proc `$`*(cStr: OwnedGtkString): string = $(cStr.cstring)
```
The plan is to change the procs in gtk.nim to return `OwnedGtkString` instead of `cstring` and thus you automagically get it all in a type with memory management.

So change `g_file_get_path` etc. in gtk.nim to this:
```nim
# gtk.nim
proc g_file_get_path*(file: GFile): OwnedGtkString
proc g_file_get_uri*(file: GFile): OwnedGtkString
proc gtk_text_buffer_get_text*(buffer: GtkTextBuffer,
                               a, b: ptr GtkTextIter,
                               includeHiddenChars: cbool): OwnedGtkString
```

I just lack the understanding on where to insert my code with `OwnedGtkString` in order to have access to g_free, while being placed before the other procs mentioned so they can use `OwnedGtkString`

**Comment by PhilippMDoerner** [comment]
Okay, now we just need to figure out the "Maybe"s of the table.

**Comment by can-lehmann** [comment]
- `cairo_status_to_string`: Looking at the source code (https://gitlab.freedesktop.org/cairo/cairo/-/blob/master/src/cairo-misc.c#L77) it just return statically allocated string literals, which **must not** be deallocated.
- `gtk_string_object_get_string`: The docs say "The data is owned by the instance.", so no deallocation is required.
- `g_value_get_string`: same as above.

**Comment by PhilippMDoerner** [comment]
Oh hey, that means the PR just needs its refinement and we're done ! :smile:
